rvm: 
  - 2.0.0

before_install:
  - cd spec/javascripts/runner

install:
  - npm install
  - bundle install
  - middleman build

before_script: 
  - cd ../../../
  - chmod +x test.sh

script: ./test.sh


