rvm: 
  - 2.0.0

before_install:
  - cd spec/javascripts/runner

install:
  - npm install
  - bundle install
  - middleman build

after_install:
  - cd ../../../

before_script: 
  - chmod -R 777 test.sh

script: source test.sh


